"use client";
import { zodResolver } from "@hookform/resolvers/zod"; import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"; import { useState } from "react"; import { useForm } from "react-hook-form"; import { queryKeys } from "@/lib/api/query-keys"; import { cancelInvitation, createInvitation, getInvitations } from "./api"; import { invitationInputSchema, statuses, type InvitationInput } from "./schemas";
export function InvitationManager({ companyId }: { companyId: number }) {
  const [status, setStatus] = useState(""); const [link, setLink] = useState<string>(); const [copyStatus, setCopyStatus] = useState(""); const client = useQueryClient();
  const query = useQuery({ queryKey: [...queryKeys.invitations(companyId), { status: status || null }], queryFn: () => getInvitations(companyId, status || undefined) });
  const create = useMutation({ mutationFn: (data: InvitationInput) => createInvitation(companyId, data), onSuccess: async (data) => { setLink(data.invitationUrl); await client.invalidateQueries({ queryKey: queryKeys.invitations(companyId) }); } });
  const cancel = useMutation({ mutationFn: (id: number) => cancelInvitation(companyId, id), onSuccess: async () => client.invalidateQueries({ queryKey: queryKeys.invitations(companyId) }) });
  const form = useForm<InvitationInput>({ resolver: zodResolver(invitationInputSchema), defaultValues: { name: "", surname: "", email: "", role: "WORKER" } });
  return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-semibold">Invitations</h1><p className="mt-2 text-slate-600">Invite workers to the active company and track invitation status.</p>
    <form onSubmit={form.handleSubmit((data) => create.mutate(data))} className="mt-7 rounded-2xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-4"><Input label="First name" error={form.formState.errors.name?.message} {...form.register("name")} /><Input label="Last name" error={form.formState.errors.surname?.message} {...form.register("surname")} /><Input label="Email" type="email" error={form.formState.errors.email?.message} {...form.register("email")} /><div className="text-sm font-medium"><span>Role</span><p className="mt-1 flex h-11 items-center rounded-xl border border-slate-200 bg-slate-50 px-3 text-slate-700">Worker</p><input type="hidden" {...form.register("role")} value="WORKER" /></div></div>{create.error && <p role="alert" className="mt-4 text-sm text-red-700">{create.error.message}</p>}<button disabled={create.isPending} className="mt-5 h-11 rounded-xl bg-emerald-700 px-5 font-semibold text-white">Create invitation</button></form>
    {link && <div role="status" className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900"><p className="font-semibold">Invitation created</p><div className="mt-2 flex gap-2"><input readOnly value={link} aria-label="Invitation link" className="h-10 min-w-0 flex-1 rounded-lg border px-3" /><button type="button" onClick={async () => { try { await navigator.clipboard.writeText(link); setCopyStatus("Invitation link copied."); } catch { setCopyStatus("Could not copy the invitation link."); } }} className="rounded-lg border bg-white px-3 font-semibold">Copy</button></div><p aria-live="polite" className="mt-2">{copyStatus}</p></div>}
    <label className="mt-7 block max-w-xs text-sm font-medium">Status<select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label>{query.isError && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{query.error.message}</p>}
    <div className="mt-5 space-y-3">{query.data?.map((invitation) => <article key={invitation.id} className="flex flex-col justify-between gap-4 rounded-2xl border bg-white p-5 sm:flex-row"><div><h2 className="font-semibold">{invitation.name} {invitation.surname}</h2><p className="text-sm text-slate-600">{invitation.email} · {invitation.role}</p><p className="mt-2 text-xs text-slate-500">Created {format(invitation.createdAt)} · Expires {format(invitation.expiresAt)}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{invitation.status}</span>{invitation.status === "PENDING" && <button type="button" disabled={cancel.isPending} onClick={() => cancel.mutate(invitation.id)} className="text-sm font-semibold text-red-700">Cancel</button>}</div></article>)}</div>
  </div>;
}
function Input({ label, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { const id = `${props.name}-error`; return <label className="text-sm font-medium">{label}<input {...props} className="mt-1 h-11 w-full rounded-xl border px-3" aria-invalid={Boolean(error)} aria-describedby={error ? id : undefined} />{error && <span id={id} role="alert" className="mt-1 block text-xs text-red-700">{error}</span>}</label>; }
const format = (value: string) => new Intl.DateTimeFormat("en-AU", { dateStyle: "medium" }).format(new Date(value));
