"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { queryKeys } from "@/lib/api/query-keys";
import { activateJoinLink, createJoinLink, disableJoinLink, getJoinLinkUrl, getJoinLinks } from "./api";

export function PublicJoinLinks({ companyId }: { companyId: number }) {
  const client = useQueryClient(); const [maxUses, setMaxUses] = useState(1); const [expiresAt, setExpiresAt] = useState(""); const [link, setLink] = useState(""); const [copy, setCopy] = useState("");
  const query = useQuery({ queryKey: [...queryKeys.invitations(companyId), "public"], queryFn: () => getJoinLinks(companyId) });
  const create = useMutation({ mutationFn: () => createJoinLink(companyId, { role: "WORKER", maxUses, expiresAt }), onSuccess: async (data) => { setLink(data.joinUrl); await client.invalidateQueries({ queryKey: queryKeys.invitations(companyId) }); } });
  const disable = useMutation({ mutationFn: (id: number) => disableJoinLink(companyId, id), onSuccess: async () => client.invalidateQueries({ queryKey: queryKeys.invitations(companyId) }) });
  const activate = useMutation({ mutationFn: (id: number) => activateJoinLink(companyId, id), onSuccess: async () => client.invalidateQueries({ queryKey: queryKeys.invitations(companyId) }) }); const view = useMutation({ mutationFn: (id: number) => getJoinLinkUrl(companyId, id), onSuccess: (url) => { setLink(url); setCopy("Link loaded."); } });
  return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-semibold">Public shared links</h1><p className="mt-2 text-slate-600">Create, review and reactivate reusable Worker links while they remain within their expiry and usage quota.</p>
    <form onSubmit={(event) => { event.preventDefault(); create.mutate(); }} className="mt-7 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-3"><label className="text-sm font-medium">Maximum uses<input required type="number" min="1" max="100000" value={maxUses} onChange={(event) => setMaxUses(Number(event.target.value))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-medium">Expires at<input required type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><button disabled={create.isPending} className="mt-6 h-11 rounded-xl bg-emerald-700 px-5 font-semibold text-white">Create public link</button>{create.error && <p role="alert" className="text-red-700 sm:col-span-3">{create.error.message}</p>}</form>
    {link && <div className="mt-4 rounded-xl bg-emerald-50 p-4"><div className="flex gap-2"><input readOnly aria-label="Public invitation link" value={link} className="h-10 min-w-0 flex-1 rounded-lg border px-3" /><button type="button" onClick={async () => { try { await navigator.clipboard.writeText(link); setCopy("Link copied."); } catch { setCopy("Could not copy link."); } }} className="rounded-lg border bg-white px-3 font-semibold">Copy</button></div><p aria-live="polite" className="mt-2 text-sm">{copy}</p></div>}
    {query.isPending && <div aria-label="Loading public links" className="mt-5 h-48 animate-pulse rounded-2xl bg-slate-200" />}{query.isError && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{query.error.message}</p>}{query.isSuccess && !query.data.length && <div className="mt-5 rounded-2xl border border-dashed p-10 text-center">No public links found.</div>}
    <div className="mt-5 space-y-3">{view.error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{view.error.message}</p>}{query.data?.map((item) => <article key={item.id} className="flex justify-between gap-3 rounded-2xl border bg-white p-5"><div><button type="button" disabled={view.isPending || item.status !== "ACTIVE"} onClick={() => view.mutate(item.id)} className="text-left font-semibold text-emerald-700 underline-offset-4 hover:underline disabled:no-underline">Public Worker link</button><p className="text-sm text-slate-600">Used {item.currentUses} / {item.maxUses} · Remaining {item.remainingUses}</p><p className="text-xs text-slate-500">Expires {item.expiresAt ? new Date(item.expiresAt).toLocaleString("en-AU") : "—"}</p></div><div><span className="text-xs font-semibold">{item.status}</span>{item.status === "ACTIVE" && <><button type="button" disabled={view.isPending} onClick={() => view.mutate(item.id)} className="ml-3 text-sm font-semibold text-emerald-700">View link</button><button type="button" disabled={disable.isPending} onClick={() => disable.mutate(item.id)} className="ml-3 text-sm font-semibold text-red-700">Disable</button></>}{item.status === "DISABLED" && <button type="button" disabled={activate.isPending} onClick={() => activate.mutate(item.id)} className="ml-3 text-sm font-semibold text-emerald-700">Reactivate</button>}</div></article>)}</div>
  </div>;
}
