import { z } from "zod";
export const profileStatuses = ["INCOMPLETE", "COMPLETE", "SUSPENDED"] as const;
export const membershipStatuses = ["PENDING_APPROVAL", "ACTIVE", "REJECTED", "SUSPENDED"] as const;
export const workerSummarySchema = z.object({ workerProfileId: z.number(), appUserId: z.number(), fullName: z.string(), email: z.string(), phone: z.string().nullable(), abn: z.string().nullable(), gstRegistered: z.boolean().nullable(), status: z.enum(profileStatuses), membershipId: z.number(), membershipRole: z.literal("WORKER"), membershipStatus: z.enum(membershipStatuses), profileComplete: z.boolean() });
const bank = z.object({ bankName: z.string().nullable(), accountName: z.string().nullable(), bsb: z.string().nullable(), accountNumber: z.string().nullable() }); const superDetails = z.object({ fundName: z.string().nullable(), usi: z.string().nullable(), memberNumber: z.string().nullable() });
export const workerSchema = z.object({ id: z.number(), appUserId: z.number(), fullName: z.string(), email: z.string(), abn: z.string().nullable(), gstRegistered: z.boolean().nullable(), phone: z.string().nullable(), status: z.enum(profileStatuses), completedAt: z.string().nullable(), bankDetails: bank.nullable(), superDetails: superDetails.nullable(), notes: z.string().nullable(), createdAt: z.string(), updatedAt: z.string() });
export const workerAdminSchema = workerSchema.extend({ membershipId: z.number(), membershipRole: z.literal("WORKER"), membershipStatus: z.enum(membershipStatuses) });
export const profileInputSchema = z.object({ abn: z.string().trim().regex(/^(?:\d[\s-]?){11}$/, "ABN must contain 11 digits.").or(z.literal("")), gstRegistered: z.boolean(), phone: z.string().trim().max(30), bankDetails: z.object({ bankName: z.string().trim().max(100), accountName: z.string().trim().max(150), bsb: z.string().trim().regex(/^\d{3}-?\d{3}$/, "BSB must contain 6 digits.").or(z.literal("")), accountNumber: z.string().trim().regex(/^\d{4,20}$/, "Use 4 to 20 digits.").or(z.literal("")) }), superDetails: z.object({ fundName: z.string().trim().max(150), usi: z.string().trim().max(50), memberNumber: z.string().trim().max(100) }), notes: z.string().trim().max(1000) });
export type Worker = z.infer<typeof workerSchema>; export type ProfileInput = z.input<typeof profileInputSchema>;
