"use client";
import { useEffect, useRef, useState } from "react"; import { useRouter } from "next/navigation"; import type { CompanyRole } from "@/lib/auth/types"; import { usePromoteWorker, useWorker, useWorkerStatus } from "./hooks";
type PromotionRole = "MANAGER" | "FINANCE";
export function WorkerDetail({ companyId, workerId, actorRole }: { companyId: number; workerId: number; actorRole: CompanyRole }) { const query = useWorker(companyId, workerId); if (query.isPending) return <div className="mt-8 h-80 animate-pulse rounded-2xl bg-slate-200" />; if (query.isError) return <div role="alert" className="mt-8 rounded-xl bg-red-50 p-5 text-red-800">{query.error.message}</div>; return <Loaded companyId={companyId} workerId={workerId} actorRole={actorRole} worker={query.data} />; }
function Loaded({ companyId, workerId, actorRole, worker }: { companyId: number; workerId: number; actorRole: CompanyRole; worker: NonNullable<ReturnType<typeof useWorker>["data"]> }) {
  const status = useWorkerStatus(companyId, workerId); const promote = usePromoteWorker(companyId, worker.membershipId); const router = useRouter(); const [dialogOpen, setDialogOpen] = useState(false); const [role, setRole] = useState<PromotionRole | null>(null); const trigger = useRef<HTMLButtonElement>(null); const suspended = worker.membershipStatus === "SUSPENDED"; const canPromote = actorRole === "OWNER" || actorRole === "ADMIN";
  const close = () => { setDialogOpen(false); setRole(null); requestAnimationFrame(() => trigger.current?.focus()); };
  return <><article className="mt-8 rounded-2xl border bg-white p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b pb-6 sm:flex-row"><div><h2 className="text-2xl font-semibold">{worker.fullName}</h2><p className="mt-1 text-slate-600">{worker.email}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={status.isPending} onClick={() => status.mutate(!suspended)} className="h-10 rounded-xl border px-4 text-sm font-semibold">{suspended ? "Reactivate membership" : "Suspend membership"}</button>{canPromote && <button ref={trigger} type="button" onClick={() => setDialogOpen(true)} className="h-10 rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white">Promote worker</button>}</div></div>{(status.error || promote.error) && <p role="alert" className="mt-4 text-red-700">{(status.error || promote.error)?.message}</p>}<dl className="mt-6 grid gap-5 sm:grid-cols-2"><Data term="Membership role" value={worker.membershipRole} /><Data term="Membership status" value={worker.membershipStatus} /><Data term="Profile status" value={worker.status} /><Data term="Phone" value={worker.phone || "Not provided"} /><Data term="ABN" value={worker.abn || "Not provided"} /><Data term="GST registered" value={worker.gstRegistered ? "Yes" : "No"} /><Data term="Bank" value={worker.bankDetails?.bankName || "Not provided"} /><Data term="Account number" value={worker.bankDetails?.accountNumber ? `•••• ${worker.bankDetails.accountNumber.slice(-4)}` : "Not provided"} /></dl></article>{dialogOpen && <PromotionDialog role={role} setRole={setRole} pending={promote.isPending} onCancel={close} onConfirm={() => { if (role) promote.mutate(role, { onSuccess: () => router.push("/workers") }); }} />}</>;
}
function PromotionDialog({ role, setRole, pending, onCancel, onConfirm }: { role: PromotionRole | null; setRole: (role: PromotionRole) => void; pending: boolean; onCancel: () => void; onConfirm: () => void }) {
  const dialog = useRef<HTMLDivElement>(null); useEffect(() => { const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onCancel(); if (event.key !== "Tab") return; const controls = dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled])'); if (!controls?.length) return; const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", key); return () => { document.body.style.overflow = overflow; document.removeEventListener("keydown", key); }; }, [onCancel, pending]);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><div ref={dialog} role="alertdialog" aria-modal="true" aria-labelledby="promote-title" aria-describedby="promote-description" className="w-full max-w-md rounded-2xl bg-white p-6"><h2 id="promote-title" className="text-lg font-semibold">Promote worker</h2><p id="promote-description" className="mt-2 text-sm text-slate-600">This person will leave the Workers list. This action cannot change them back to WORKER; reversal requires a separate authorised membership workflow.</p><fieldset className="mt-5 flex gap-4"><legend className="mb-2 text-sm font-semibold">Choose the new role</legend>{(["MANAGER", "FINANCE"] as const).map((value) => <label key={value} className="flex items-center gap-2"><input type="radio" checked={role === value} onChange={() => setRole(value)} />{value}</label>)}</fieldset><div className="mt-6 flex justify-end gap-3"><button type="button" autoFocus onClick={onCancel} disabled={pending} className="h-10 rounded-xl border px-4">Cancel</button><button type="button" onClick={onConfirm} disabled={pending || !role} className="h-10 rounded-xl bg-emerald-700 px-4 font-semibold text-white disabled:opacity-50">{pending ? "Promoting…" : role ? `Promote to ${role}` : "Choose a role"}</button></div></div></div>;
}
function Data({ term, value }: { term: string; value: string }) { return <div><dt className="text-xs uppercase text-slate-500">{term}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
