"use client";
import { useEffect, useRef, useState } from "react"; import Link from "next/link"; import { useRate, useSetRateActive } from "./hooks"; import { label, RateError } from "./ui";
export function RateDetail({ companyId, rateId, canManage }: { companyId: number; rateId: number; canManage: boolean }) {
  const query = useRate(companyId, rateId); const mutation = useSetRateActive(companyId, rateId); const [confirm, setConfirm] = useState<boolean | null>(null); const trigger = useRef<HTMLButtonElement>(null);
  if (query.isPending) return <div className="mt-8 h-80 animate-pulse rounded-2xl bg-slate-200" />; if (query.isError) return <div className="mt-8"><RateError error={query.error} retry={() => query.refetch()} /></div>;
  const rate = query.data; const close = () => { setConfirm(null); requestAnimationFrame(() => trigger.current?.focus()); };
  return <>{mutation.error && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{mutation.error instanceof Error ? mutation.error.message : "Could not update the rate status."}</div>}<article className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:justify-between"><div><h2 className="text-2xl font-semibold">{rate.positionName}</h2><p className="mt-1 text-sm text-slate-600">{rate.projectName} · {formatDate(rate.effectiveFrom)} to {rate.effectiveTo ? formatDate(rate.effectiveTo) : "Open-ended"}</p></div>{canManage && <div className="flex gap-2"><Link href={`/rates/${rateId}/edit`} className="h-10 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Edit</Link><button ref={trigger} type="button" onClick={() => setConfirm(!rate.active)} className="h-10 rounded-xl border border-slate-300 px-4 text-sm font-semibold">{rate.active ? "Deactivate" : "Reactivate"}</button></div>}</div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase text-slate-500"><th className="pb-3">Rate type</th><th className="pb-3">Calculation</th><th className="pb-3">Value</th><th className="pb-3">Description</th><th className="pb-3">Status</th></tr></thead><tbody>{rate.items.map((item) => <tr key={item.id} className="border-b border-slate-100"><td className="py-4 font-medium">{label(item.rateType)}</td><td>{label(item.calculationType)}</td><td>{item.value}</td><td>{item.description || "—"}</td><td>{item.active ? "Active" : "Inactive"}</td></tr>)}</tbody></table></div><p className="mt-5 text-xs text-slate-500">Displayed values are stored rate configuration. Financial totals are calculated authoritatively by the backend.</p></article>{confirm !== null && <StatusDialog active={confirm} pending={mutation.isPending} onCancel={close} onConfirm={() => mutation.mutate(confirm, { onSuccess: close })} />}</>;
}
function StatusDialog({ active, pending, onCancel, onConfirm }: { active: boolean; pending: boolean; onCancel: () => void; onConfirm: () => void }) { const dialog = useRef<HTMLDivElement>(null); useEffect(() => { const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onCancel(); if (event.key !== "Tab") return; const controls = dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]), [href], [tabindex]:not([tabindex="-1"])'); if (!controls?.length) return; const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", key); return () => { document.body.style.overflow = overflow; document.removeEventListener("keydown", key); }; }, [onCancel, pending]); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" onMouseDown={(event) => { if (event.currentTarget === event.target && !pending) onCancel(); }}><div ref={dialog} role="alertdialog" aria-modal="true" aria-labelledby="rate-status-title" aria-describedby="rate-status-description" className="w-full max-w-md rounded-2xl bg-white p-6"><h2 id="rate-status-title" className="text-lg font-semibold">{active ? "Reactivate" : "Deactivate"} this rate period?</h2><p id="rate-status-description" className="mt-2 text-sm text-slate-600">Historical records are retained. Reactivation may fail if the period overlaps another active rate.</p><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={pending} onClick={onCancel} className="h-10 rounded-xl border px-4">Cancel</button><button type="button" autoFocus disabled={pending} onClick={onConfirm} className="h-10 rounded-xl bg-emerald-700 px-4 text-white">{pending ? "Updating…" : "Confirm"}</button></div></div></div>; }
const formatDate = (value: string) => new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
