"use client";
import Link from "next/link";
import { Bell, CheckCheck } from "lucide-react";
import { useState } from "react";
import { useMarkAllNotificationsRead, useMarkNotificationRead, useNotifications, useUnreadNotificationCount } from "./hooks";

export function NotificationBell({ companyId }: { companyId: number }) {
  const [open, setOpen] = useState(false); const list = useNotifications(companyId); const count = useUnreadNotificationCount(companyId); const mark = useMarkNotificationRead(companyId); const markAll = useMarkAllNotificationsRead(companyId);
  return <div className="relative"><button type="button" aria-label={count.data ? `${count.data} unread notifications` : "Notifications"} aria-expanded={open} onClick={() => setOpen((value) => !value)} className="relative rounded-lg p-2 text-slate-600 hover:bg-slate-100"><Bell size={19} />{Boolean(count.data) && <span className="absolute -right-0.5 -top-0.5 grid min-w-4 place-items-center rounded-full bg-red-600 px-1 text-[10px] font-bold leading-4 text-white">{count.data! > 99 ? "99+" : count.data}</span>}</button>{open && <div className="absolute right-0 z-50 mt-2 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl" style={{ width: "min(380px, calc(100vw - 2rem))" }}><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><h2 className="font-semibold">Notifications</h2><button type="button" onClick={() => markAll.mutate()} disabled={!count.data || markAll.isPending} className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700 disabled:text-slate-400"><CheckCheck size={15} />Mark all read</button></div><div className="max-h-96 overflow-y-auto">{list.isPending && <p className="p-5 text-sm text-slate-500">Loading notifications…</p>}{list.isError && <p className="p-5 text-sm text-red-700">{list.error.message}</p>}{list.data?.map((item) => <Link key={item.id} href={item.targetPath} onClick={() => { if (!item.read) mark.mutate(item.id); setOpen(false); }} className={`block border-b border-slate-100 px-4 py-3 hover:bg-slate-50 ${item.read ? "" : "bg-emerald-50/60"}`}><div className="flex gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${item.read ? "bg-slate-300" : "bg-emerald-600"}`} /><div><p className="text-sm font-semibold text-slate-900">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.message}</p><time className="mt-1 block text-xs text-slate-400">{formatTime(item.createdAt)}</time></div></div></Link>)}{list.isSuccess && list.data.length === 0 && <p className="p-6 text-center text-sm text-slate-500">No notifications yet.</p>}</div></div>}</div>;
}
function formatTime(value: string) { return new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
