"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Archive, Pencil, RotateCcw } from "lucide-react";
import { usePosition, useSetPositionActive } from "./hooks";
import { PositionError } from "./ui";

export function PositionDetail({ companyId, positionId }: { companyId: number; positionId: number }) {
  const [nextStatus, setNextStatus] = useState<boolean | null>(null); const triggerRef = useRef<HTMLButtonElement>(null);
  const query = usePosition(companyId, positionId); const mutation = useSetPositionActive(companyId, positionId);
  if (query.isPending) return <div aria-label="Loading position" className="mt-8 h-72 animate-pulse rounded-2xl bg-slate-200" />;
  if (query.isError) return <div className="mt-8"><PositionError message={query.error instanceof Error ? query.error.message : "Please try again."} retry={() => query.refetch()} /></div>;
  const data = query.data;
  const close = () => { setNextStatus(null); requestAnimationFrame(() => triggerRef.current?.focus()); };
  return <>{mutation.error && <p role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">{mutation.error instanceof Error ? mutation.error.message : "Could not update the position status."}</p>}<article className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-semibold text-slate-950">{data.positionName}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${data.active ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{data.active ? "Active" : "Inactive"}</span></div><p className="mt-2 text-sm text-slate-600">{data.projectName}</p></div><div className="flex flex-wrap gap-2"><Link href={`/positions/${positionId}/edit`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-300 px-3 text-sm font-semibold"><Pencil size={16} aria-hidden="true" />Edit</Link><button ref={triggerRef} type="button" onClick={() => setNextStatus(!data.active)} className={`inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-sm font-semibold ${data.active ? "border-red-200 text-red-700" : "border-emerald-200 text-emerald-800"}`}>{data.active ? <Archive size={16} aria-hidden="true" /> : <RotateCcw size={16} aria-hidden="true" />}{data.active ? "Deactivate" : "Reactivate"}</button></div></div><dl className="mt-6 grid gap-6 sm:grid-cols-2"><Datum term="Project" value={data.projectName} /><Datum term="Company" value={data.companyName} /><Datum term="Created" value={formatDate(data.createdAt)} /><Datum term="Last updated" value={formatDate(data.updatedAt)} /></dl></article>{nextStatus !== null && <StatusDialog active={nextStatus} name={data.positionName} pending={mutation.isPending} onCancel={close} onConfirm={() => mutation.mutate(nextStatus, { onSuccess: close })} />}</>;
}
function StatusDialog({ active, name, pending, onCancel, onConfirm }: { active: boolean; name: string; pending: boolean; onCancel: () => void; onConfirm: () => void }) {
  const dialog = useRef<HTMLDivElement>(null); const verb = active ? "Reactivate" : "Deactivate";
  useEffect(() => { const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; const handler = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onCancel(); if (event.key !== "Tab") return; const items = dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]), [href], [tabindex]:not([tabindex="-1"])'); if (!items?.length) return; const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", handler); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", handler); }; }, [onCancel, pending]);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" onMouseDown={(e) => { if (e.currentTarget === e.target && !pending) onCancel(); }}><div ref={dialog} role="alertdialog" aria-modal="true" aria-labelledby="position-status-title" aria-describedby="position-status-description" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 id="position-status-title" className="text-lg font-semibold">{verb} {name}?</h2><p id="position-status-description" className="mt-2 text-sm text-slate-600">{active ? "This position will become available again." : "This marks the position inactive without deleting historical records."}</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} disabled={pending} className="h-10 rounded-xl border border-slate-300 px-4 text-sm font-semibold">Cancel</button><button type="button" autoFocus onClick={onConfirm} disabled={pending} className={`h-10 rounded-xl px-4 text-sm font-semibold text-white ${active ? "bg-emerald-700" : "bg-red-700"}`}>{pending ? "Updating…" : verb}</button></div></div></div>;
}
function Datum({ term, value }: { term: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{term}</dt><dd className="mt-1 text-sm font-medium text-slate-900">{value}</dd></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
