"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { BriefcaseBusiness, Eye, Pencil, Plus, Search } from "lucide-react";
import { useActiveProjects, usePositions } from "./hooks";
import { PageHeader, PositionError } from "./ui";

export function PositionList({ companyId }: { companyId: number }) {
  const [activeOnly, setActiveOnly] = useState(true); const [projectId, setProjectId] = useState<number>(); const [search, setSearch] = useState("");
  const query = usePositions(companyId, activeOnly, projectId); const projects = useActiveProjects(companyId);
  const data = useMemo(() => { const term = search.trim().toLocaleLowerCase(); return term ? (query.data ?? []).filter((item) => item.positionName.toLocaleLowerCase().includes(term)) : (query.data ?? []); }, [query.data, search]);
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Project operations" title="Positions" description="Manage project positions for the active company." action={<Link href="/positions/new" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800"><Plus size={18} aria-hidden="true" />New position</Link>} />
    <div className="mt-8 grid gap-4 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[minmax(0,1fr)_minmax(180px,260px)_auto] sm:items-center"><label className="relative"><span className="sr-only">Search positions by name</span><Search size={18} aria-hidden="true" className="absolute left-3 top-3 text-slate-400" /><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search positions" className="h-11 w-full rounded-xl border border-slate-300 pl-10 pr-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100" /></label><label><span className="sr-only">Filter by project</span><select value={projectId ?? ""} onChange={(e) => setProjectId(e.target.value ? Number(e.target.value) : undefined)} className="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"><option value="">All projects</option>{projects.data?.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="flex items-center gap-3 text-sm font-medium text-slate-700"><input type="checkbox" checked={activeOnly} onChange={(e) => setActiveOnly(e.target.checked)} className="size-5 accent-emerald-700" />Active only</label></div>
    <div className="mt-5">{query.isPending && <div aria-label="Loading positions" className="grid gap-4 lg:grid-cols-2">{[0,1,2,3].map((i) => <div key={i} className="h-48 animate-pulse rounded-2xl bg-slate-200" />)}</div>}{query.isError && <PositionError message={query.error instanceof Error ? query.error.message : "Please try again."} retry={() => query.refetch()} />}{query.isSuccess && !data.length && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><BriefcaseBusiness className="mx-auto text-slate-400" aria-hidden="true" /><h2 className="mt-3 font-semibold">No positions found</h2><p className="mt-1 text-sm text-slate-600">Adjust the filters or create a position.</p></div>}{data.length > 0 && <div className="grid gap-4 lg:grid-cols-2">{data.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-950">{item.positionName}</h2><p className="mt-1 text-sm text-slate-600">{item.projectName}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.active ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{item.active ? "Active" : "Inactive"}</span></div><p className="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-600">Updated {formatDate(item.updatedAt)}</p><div className="mt-4 flex gap-2"><Link href={`/positions/${item.id}`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-300 px-3 text-sm font-semibold"><Eye size={16} aria-hidden="true" />View</Link><Link href={`/positions/${item.id}/edit`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-300 px-3 text-sm font-semibold"><Pencil size={16} aria-hidden="true" />Edit</Link></div></article>)}</div>}</div>
  </div>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("en-AU", { dateStyle: "medium" }).format(new Date(value)); }
